#!/bin/bash
DB="databases25"
USER="root"
PASS="root"

mysql -u "$USER" -p"$PASS" "$DB" < "continebt.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "location.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "festival.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "genre.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "subgenre.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "artist.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "band.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "band_artist.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "artist_subgenre.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "band_subgenre.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "ticket_type.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "purchase_type.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "performance_type.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "role.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "experience.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "visitor.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "building.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "event.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "ticket.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "resale_queue.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "buyer.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "staff.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "equipment.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "performance.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "artist_performance.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "review.sql"
mysql -u "$USER" -p"$PASS" "$DB" < "criteria.sql"
