#!/bin/bash
DB="databases25"
#USER="root"
#PASS="root"

#SET GLOBAL max_allowed_packet=1073741824;

#mysql -u "$USER" -p"$PASS" "$DB" < "continent.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "location.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "festival.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "genre.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "subgenre.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "artist.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "band.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "band_artist.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "artist_subgenre.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "band_subgenre.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "ticket_type.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "purchase_type.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "performance_type.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "role.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "experience.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "visitor.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "building.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "event.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "ticket.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "resale_queue.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "buyer.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "staff.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "equipment.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "performance.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "artist_performance.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "review.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "continent.sql"
mysql "$DB" < "continent.sql"
mysql "$DB" < "location.sql"
mysql "$DB" < "festival.sql"
mysql "$DB" < "genre.sql"
mysql "$DB" < "subgenre.sql"
mysql "$DB" < "artist.sql"
mysql "$DB" < "band.sql"
mysql "$DB" < "band_artist.sql"
mysql "$DB" < "artist_subgenre.sql"
mysql "$DB" < "band_subgenre.sql"
mysql "$DB" < "ticket_type.sql"
mysql "$DB" < "purchase_type.sql"
mysql "$DB" < "performance_type.sql"
mysql "$DB" < "role.sql"
mysql "$DB" < "experience.sql"
mysql "$DB" < "visitor.sql"
mysql "$DB" < "building.sql"
mysql "$DB" < "event.sql"
mysql "$DB" < "ticket.sql"
mysql "$DB" < "resale_queue.sql"
mysql "$DB" < "buyer.sql"
mysql "$DB" < "staff.sql"
mysql "$DB" < "equipment.sql"
mysql "$DB" < "performance.sql"
mysql "$DB" < "artist_performance.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "review.sql"
#mysql -u "$USER" -p"$PASS" "$DB" < "criteria.sql"mysql -u "$USER" -p"$PASS" "$DB" < "criteria.sql"
