INSERT INTO `artist` (`name`, `stage_name`, `birthdate`, `site`, `instagram_profile`, `image_url`) VALUES
('Kayla Gallagher', 'dthomas', '1989-02-12', 'http://petersen.com/', 'https://instagram.com/dthomas', 'https://dummyimage.com/182x543'),
('Ashley Brown', 'christinarios', '1991-11-08', 'http://www.evans.com/', 'https://instagram.com/christinarios', 'https://www.lorempixel.com/460/248'),
('Cheryl Richardson', 'annaroberts', '1978-04-10', 'http://www.house.com/', 'https://instagram.com/annaroberts', 'https://www.lorempixel.com/618/664'),
('Brooke Thomas', 'smithrebecca', '1982-12-28', 'http://www.anderson.org/', 'https://instagram.com/smithrebecca', 'https://placekitten.com/878/550'),
('Mrs. Angela Jones', 'andersonbeth', '2002-03-19', 'https://www.dixon-johnson.com/', 'https://instagram.com/andersonbeth', 'https://placekitten.com/1012/587'),
('Michael Escobar', 'danaandersen', '1966-02-26', 'https://www.weaver.com/', 'https://instagram.com/danaandersen', 'https://dummyimage.com/303x433'),
('Edward Turner', 'terrythomas', '1977-04-05', 'http://raymond.info/', 'https://instagram.com/terrythomas', 'https://dummyimage.com/627x271'),
('Evelyn Davis', 'paulapark', '1982-10-01', 'http://www.campbell.com/', 'https://instagram.com/paulapark', 'https://placekitten.com/718/358'),
('Leslie Shaw', 'omcintosh', '1997-10-17', 'https://pearson-russo.net/', 'https://instagram.com/omcintosh', 'https://placekitten.com/161/19'),
( 'Eric Johnson', 'williamsaaron', '1986-06-03', 'https://williams.com/', 'https://instagram.com/williamsaaron', 'https://placeimg.com/311/230/any'),
( 'Zachary Gonzalez', 'katherinemcfarland', '2000-07-23', 'http://brown.com/', 'https://instagram.com/katherinemcfarland', 'https://placekitten.com/504/749'),
('Karen Haynes', 'brandon92', '1968-08-05', 'http://moore.biz/', 'https://instagram.com/brandon92', 'https://dummyimage.com/846x233'),
('Joshua Smith', 'vasquezrebecca', '1997-01-27', 'https://barnes.info/', 'https://instagram.com/vasquezrebecca', 'https://placeimg.com/297/802/any'),
('Janice Koch', 'qpatterson', '2004-10-29', 'http://singleton.biz/', 'https://instagram.com/qpatterson', 'https://www.lorempixel.com/152/996'),
('Jonathan Lynch', 'monica48', '1999-06-01', 'https://www.jackson.com/', 'https://instagram.com/monica48', 'https://www.lorempixel.com/42/670'),
('Timothy Whitaker', 'wesleyreynolds', '1980-02-16', 'https://www.ward.com/', 'https://instagram.com/wesleyreynolds', 'https://placeimg.com/477/332/any'),
('Michelle White', 'cbrooks', '1970-01-16', 'http://miller.com/', 'https://instagram.com/cbrooks', 'https://placekitten.com/96/491'),
('Maria Myers', 'wellsmichelle', '1979-03-08', 'http://houston.com/', 'https://instagram.com/wellsmichelle', 'https://www.lorempixel.com/171/755'),
('Amy Rose', 'ryanreynolds', '1989-10-30', 'https://www.lewis-rose.com/', 'https://instagram.com/ryanreynolds', 'https://www.lorempixel.com/65/107'),
('Scott Lee', 'briggsmatthew', '1994-02-14', 'http://www.gutierrez.info/', 'https://instagram.com/briggsmatthew', 'https://www.lorempixel.com/170/800'),
('Richard Farrell', 'brittanygarcia', '2000-03-04', 'https://www.davis.com/', 'https://instagram.com/brittanygarcia', 'https://placeimg.com/945/267/any'),
('Brittany Moore', 'christopherlewis', '1985-05-13', 'https://www.mcguire.org/', 'https://instagram.com/christopherlewis', 'https://www.lorempixel.com/481/553'),
('Linda Kline', 'darrentaylor', '1990-10-11', 'http://www.mendez-anderson.com/', 'https://instagram.com/darrentaylor', 'https://www.lorempixel.com/801/534'),
('Jose Hobbs', 'welchjason', '1995-12-26', 'http://www.hendricks-brown.com/', 'https://instagram.com/welchjason', 'https://dummyimage.com/2x797'),
('Theresa Mcbride', 'yparker', '1968-11-23', 'https://anderson-kerr.info/', 'https://instagram.com/yparker', 'https://dummyimage.com/761x113'),
('Laura Coleman MD', 'richardvalencia', '1995-10-19', 'http://payne.com/', 'https://instagram.com/richardvalencia', 'https://www.lorempixel.com/21/444'),
('Joseph Spencer', 'alison46', '1979-03-17', 'http://chavez.org/', 'https://instagram.com/alison46', 'https://placeimg.com/717/492/any'),
('Sandra Ward', 'gabriel03', '1967-10-02', 'http://nicholson.com/', 'https://instagram.com/gabriel03', 'https://dummyimage.com/448x48'),
('Pamela Serrano', 'amandavasquez', '1978-05-12', 'http://long.com/', 'https://instagram.com/amandavasquez', 'https://placekitten.com/373/759'),
('John Mcpherson', 'parkertiffany', '1966-12-12', 'http://www.best.biz/', 'https://instagram.com/parkertiffany', 'https://placeimg.com/673/322/any'),
('Tiffany Johnson', 'amberhayes', '1980-08-23', 'http://martin.com/', 'https://instagram.com/amberhayes', 'https://placekitten.com/769/771'),
('Cynthia Diaz', 'ashley15', '1975-11-12', 'http://www.munoz-mcbride.com/', 'https://instagram.com/ashley15', 'https://placeimg.com/940/55/any'),
('Anthony Noble', 'alejandro61', '2004-05-02', 'http://www.wu.com/', 'https://instagram.com/alejandro61', 'https://placeimg.com/739/67/any'),
('Leslie Acevedo', 'obrock', '1964-09-01', 'http://campbell.com/', 'https://instagram.com/obrock', 'https://www.lorempixel.com/867/376'),
('Ralph Mahoney', 'lauragreen', '1981-03-16', 'https://www.day.com/', 'https://instagram.com/lauragreen', 'https://placeimg.com/190/485/any'),
('Julie Hanson', 'albert10', '1987-12-15', 'https://thompson-andrews.net/', 'https://instagram.com/albert10', 'https://placeimg.com/570/132/any'),
('William Woods', 'davidmoore', '1991-12-23', 'https://davis-wilcox.com/', 'https://instagram.com/davidmoore', 'https://placekitten.com/344/920'),
('Toni Lee', 'gonzalezchristopher', '1971-10-29', 'http://king-turner.org/', 'https://instagram.com/gonzalezchristopher', 'https://placeimg.com/692/487/any'),
('Miranda Johnson', 'robertmoody', '1988-05-12', 'https://smith-soto.com/', 'https://instagram.com/robertmoody', 'https://placeimg.com/102/604/any'),
('Melissa Summers', 'dawn61', '1983-12-29', 'http://christensen.com/', 'https://instagram.com/dawn61', 'https://www.lorempixel.com/852/193'),
('James Hodges', 'christopher02', '1995-10-09', 'http://james.com/', 'https://instagram.com/christopher02', 'https://placekitten.com/293/828'),
('Peter Williams', 'cscott', '1978-09-22', 'http://travis.info/', 'https://instagram.com/cscott', 'https://placeimg.com/854/599/any'),
('Anna Michael', 'qkeller', '1968-08-17', 'http://marsh.com/', 'https://instagram.com/qkeller', 'https://placeimg.com/545/871/any'),
('Monica Cantu', 'kevin43', '2003-11-23', 'http://www.gentry.info/', 'https://instagram.com/kevin43', 'https://dummyimage.com/786x285'),
('Ashley Ferguson', 'foxeric', '1982-01-04', 'http://www.mills.org/', 'https://instagram.com/foxeric', 'https://placekitten.com/22/333'),
('Dakota Blanchard', 'crystal55', '2004-11-23', 'http://www.cabrera.org/', 'https://instagram.com/crystal55', 'https://placeimg.com/610/180/any'),
('James Day', 'shannonsteele', '1976-11-24', 'http://hunter.com/', 'https://instagram.com/shannonsteele', 'https://dummyimage.com/576x287'),
('Jennifer Bradshaw', 'susan51', '1983-09-02', 'http://torres-ramirez.biz/', 'https://instagram.com/susan51', 'https://placeimg.com/335/930/any'),
('Christine Martinez', 'peterclark', '1982-10-24', 'https://www.barker-cooper.com/', 'https://instagram.com/peterclark', 'https://www.lorempixel.com/343/1023'),
('Stacy Anderson', 'justinwells', '1998-10-27', 'https://miller-stokes.com/', 'https://instagram.com/justinwells', 'https://placeimg.com/936/775/any');
