#!/bin/bash

DB="databases25"
DIR="inserts"

mysql "$DB" < "$DIR/continent.sql"
mysql "$DB" < "$DIR/location.sql"
mysql "$DB" < "$DIR/festival.sql"
mysql "$DB" < "$DIR/genre.sql"
mysql "$DB" < "$DIR/subgenre.sql"
mysql "$DB" < "$DIR/artist.sql"
mysql "$DB" < "$DIR/band.sql"
mysql "$DB" < "$DIR/band_artist.sql"
mysql "$DB" < "$DIR/artist_subgenre.sql"
mysql "$DB" < "$DIR/band_subgenre.sql"
mysql "$DB" < "$DIR/ticket_type.sql"
mysql "$DB" < "$DIR/purchase_type.sql"
mysql "$DB" < "$DIR/performance_type.sql"
mysql "$DB" < "$DIR/role.sql"
mysql "$DB" < "$DIR/experience.sql"
mysql "$DB" < "$DIR/visitor.sql"
mysql "$DB" < "$DIR/building.sql"
mysql "$DB" < "$DIR/event.sql"
mysql "$DB" < "$DIR/ticket.sql"
#mysql "$DB" < "$DIR/resale_queue.sql"
mysql "$DB" < "$DIR/buyer.sql"
mysql "$DB" < "$DIR/staff.sql"
mysql "$DB" < "$DIR/equipment.sql"
mysql "$DB" < "$DIR/performance.sql"
mysql "$DB" < "$DIR/artist_performance.sql"
mysql "$DB" < "$DIR/criteria.sql"
mysql "$DB" < "$DIR/review.sql"
mysql "$DB" < "$DIR/more_reviews.sql"
